spring.application.name=TercihRobotu




spring.datasource.url=jdbc:postgresql://localhost:5432/TercihRobotu
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.servlet.session.persistent=true
server.servlet.session.timeout=1800